# This is a basic workflow to help you get started with Actions

name: InternCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  iothubname: "yardvisibilityiothubhiramoto3"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  MakeIoTHubsAndDPS:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: login azure
        run: az login # login azure manually
      - name: Create IoT Hubs
        run: |
          #$iothubname = "yardvisibilityiothubhiramoto3"
          $resourceGroup = "InternDev"                 
          $location = "eastus"  
          az iot hub create --name $iothubname --resource-group $resourceGroup --location $location --sku S1 --mintls 1.2
      - name: Make namespace of event hubs
        run: |
          $eventhubsnamespace = "yardvisibilityeventhubhiramoto2"
          #$resourceGroup = "InternDev"
          #$location = "eastus"
          # EventHubs 名前空間作成
          az eventhubs namespace create --resource-group $resourceGroup --name $eventhubsnamespace --location $location --sku Basic

