# This is a basic workflow to help you get started with Actions

name: InternCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  LoginAzure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: login azure
        run: az login
      - name: azure command
        run: az iot hub create --name "yardvisibilityiothubhiramotogitactions" --resource-group "InternDev" --location "eastus" --sku S1 --mintls 1.2
      - name: Run a one-line script
        run: echo ${{ secrets.SECRETNAME }}
#       - name: login azure
#         run: az login -u hiramoto.atsumu@kk.jp.panasonic.com -p Pana2860
#       - name: Login Azure
#         run: az login -u ${{ secrets.USER_ID }} -p ${{ secrets.USER_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
