name: InternCI_cert

on:
  workflow_dispatch:
env:
  iothubname: "yardvisibilityiothubhiramoto3"
  eventhubsnamespace: "yardvisibilityeventhubhiramoto3"
  resourceGroup: "InternDev"
  location: "eastus"
  endpointsubscriptionid: ${{ secrets.ENDPOINTSUBSCRIPTIONID }}
  dpsname: "yardvisibilitydpshiramoto2"
  rootCert: "./Cert/YardTrackingUS.production.Root.pem"
  rootCertName: "YardTrackingUS.production.Root"
  enrollment_id: "YardTrackingQA1.production.ANPR"
  intermediateCart: "./Cert/YardTrackingUS.production.ANPR.CA.pem"
  initial_twin_properties: "{}"
  initial_twin_tags: "{'anpr': 'true', 'reference_station': 'false', 'app_id': 'YardTrackingUS', 'environment': 'production'}"

jobs:
  MakeIoTHubsAndDPS:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Login Azure
        run: az login # login azure manually
      - name: Upload cert pem file
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az iot dps certificate create --dps-name $dpsname --resource-group $resourceGroup --verified true --name $rootCertName --path $rootCert
      - name: Make enrollment group
        run: az iot dps enrollment-group create -g $resourceGroup --dps-name $dpsname --enrollment-id $enrollment_id --iot-hubs $iothubs --allocation-policy hashed --edge-enabled true --certificate-path $intermediateCart --initial-twin-properties $initial_twin_properties --initial-twin-tags $initial_twin_tags
